dog_name = "Maika"
dog_type = "Husky"
owner_name = "Donatas"
picture = "maika-donatas.jpeg"
extra = [
    "Alleen snoepjes als ze een kunstje doet",
    "Kan goed met bijna alle honden"
]

[[days]]
day = 0
times = [
    "12:30",
    "17:30"
]

[[days]]
day = 1
times = [
    "12:30",
    "17:30"
]

[[days]]
day = 2
times = [
    "12:30",
    "17:30"
]

[[days]]
day = 3
times = [
    "20:00"
]

[[days]]
day = 4
times = [
    "12:30",
    "17:30"
]

[[days]]
day = 5
times = [
    "12:30",
    "17:30"
]

[[days]]
day = 6
times = [
    "12:30",
    "17:30"
]